### PR TITLE
fix(handler) replaced deprecated APIs with PDK

### LINKED ISSUE #11: OpenWhisk Plugin Error using deprecated `kong.tools.responses`
The error `module 'kong.tools.responses' not found` occurs on initialization

(See trace attached)

image

It appears that the relevant line may be in [kong-plugin-openwhisk/kong/plugins/openwhisk/handler.lua](https://github.com/Kong/kong-plugin-openwhisk/blob/master/kong/plugins/openwhisk/handler.lua)... with the line `local responses     = require "kong.tools.responses"`.  I'm not a lua developer... so, not in the best position to make a fix and submit a PR...

This [Changelog](https://github.com/Kong/kong/blob/master/CHANGELOG.md#plugins-3) shows the below statement regarding plugins (which is an indication of the issue) 

`The kong.tools.responses module was removed. Please use kong.response.exit from the PDK instead. You might want to use kong.log.err to log internal server errors as well.`

### PR DESCRIPTION
**Pull request by devadvocado**
- replaced `kong.tools.responses` with `kong.response`
- replaced `kong.tools.public` get_body_args with `kong.request.get_body`
- replaced `kong.tools.utils` table_merge with `kong.table.merge`

Issues resolved
Fix #11

### CODE REVIEW

File: kong/plugins/openwhisk/handler.lua [hunk 1]
```diff
@@ -106,13 +101,14 @@ function OpenWhisk:access(config)
...
-    return responses.send_HTTP_METHOD_NOT_ALLOWED()
+    return kong.response.exit(405, { message = "Method not allowed" })
   end
 
   -- get parameters
   local body, err = retrieve_parameters()
   if err then
-    return responses.send_HTTP_BAD_REQUEST(err)
+    kong.log.err(err)
+    return kong.response.exit(400, { message = "Cannot process the request due to a client error" })
```
Comment (gszr) [inline kong/plugins/openwhisk/handler.lua]: Let's do `{message = err}` in here as this is a 400 - and no need for `kong.log.err` in this case.

Comment (devadvocado) [reply kong/plugins/openwhisk/handler.lua]: done 👍
